name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo.lock
      id: cache
      uses: actions/cache@v3.2.3
      with:
        path: '**/target'
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ./actix_web_2023
      run: cargo build --verbose

    - name: Run tests
      working-directory: ./actix_web_2023
      run: cargo test --verbose
